services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  generatetoken:
    build:
      context: ./GenerateToken
    ports:
      - "8000:3080"
  verifytoken:
    build:
      context: ./VerifyToken
    ports:
      - "8005:3085"
  fronttoken:
    build:
      context: ./Front
    ports:
      - "8009:4200"
    environment:
      - PORT=4200